const NAVBAR_TITLE = 'Pathfinding Visualizer';

const DEFAULT_WIDTH = 10;

const DEFAULT_HEIGHT = 40;

const DFS_ALGORITHM = 'DFS';

const BFS_ALGORITHM = 'BFS';

const DIJKSTRA_ALGORITHM = 'DIJKSTRA';

export {
  NAVBAR_TITLE,
  DEFAULT_WIDTH,
  DEFAULT_HEIGHT,
  BFS_ALGORITHM,
  DFS_ALGORITHM,
  DIJKSTRA_ALGORITHM
}
