const NAVBAR_TITLE = 'Pathfinding Visualizer'

const DEFAULT_WIDTH = 20;

const DEFAULT_HEIGHT = 10;

const DFS_ALGORITHM = 'DFS'

const BFS_ALGORITHM = 'BFS'

const DJAKSTRA_ALGORITHM = 'DJAKSTRA'

export {
  NAVBAR_TITLE,
  DEFAULT_WIDTH,
  DEFAULT_HEIGHT,
  BFS_ALGORITHM,
  DFS_ALGORITHM,
  DJAKSTRA_ALGORITHM
}
